background {
    monitor =
    path = screenshot  # делает скриншот рабочего стола
    blur_passes = 2
    blur_size = 7
}

general {
    grace = 1
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    outer_color = rgb(151515)
    inner_color = rgb(183, 189, 248)
    font_color = rgb(10, 10, 10)
    placeholder_text = <i>Password</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    text = $TIME
    font_size = 60
    font_family = Noto Sans
    color = rgba(255, 255, 255, 1.0)
    position = 0, 100
    halign = center
    valign = center
}
